### ISSUE TITLE
抄rbatis  也不能这么抄吧，没意思啊

### ISSUE THREAD

**Issue by by965738071** [summer-os/summer-mybatis#99]

**Comment by by965738071** [comment]
支持

**Comment by Jzow** [comment]
您好，rbatis和summer mybatis都是遵循了Apache-2.0 license协议，我们需要改进这个项目有很多点，比如以下两点我们需要对他进行支持：

1. 支持oracle 驱动
2. xml解析 和 宏

（下个版本我们会更新他）

**Comment by by965738071** [comment]
但是我觉得，起码要尊重一下作者吧， 应该把rbatis 的链接放readme.md，开源精神啊。

**Comment by kotlin2018** [comment]
> 您好，rbatis和summer mybatis都是遵循了Apache-2.0 license协议，我们需要改进这个项目有很多点，比如以下两点我们需要对他进行支持：
> 
> 1. 支持oracle 驱动
> 2. xml解析 和 宏
> 
> （下个版本我们会更新他）

最起码，你得在 README.md 中标注，你是基于 rbatis 开发的吧，如果你没看过 rbatis 源码，你能做出现在这个库，你这叫窃取原作者的劳动成果，你懂么？

**Comment by Jzow** [comment]
@by965738071 @kotlin2018 是的，我认为这是必要的。

**Comment by Jzow** [comment]
check, closed

**Comment by kotlin2018** [comment]
> @by965738071 @kotlin2018 是的，我认为这是必要的。
要不直接在 READEME.md 中表达对 rbatis 的敬意，感谢 rbatis 作者的辛勤创作呗。
饮水思源啊，亲。

**Comment by kotlin2018** [comment]
> @by965738071 @kotlin2018 是的，我认为这是必要的。



> 您好，rbatis和summer mybatis都是遵循了Apache-2.0 license协议，我们需要改进这个项目有很多点，比如以下两点我们需要对他进行支持：
> 
> 1. 支持oracle 驱动
> 2. xml解析 和 宏
> 
> （下个版本我们会更新他）

是的，我认为这是必要的。
要不直接在 READEME.md 中表达对 rbatis 的敬意，感谢 rbatis 作者的辛勤创作呗。
饮水思源啊，亲。
